name = "toolhub-site"
type = "static"

[build]
  command = "echo 'No build command needed'"  # No need for a build step
  directory = "."  # Set the correct output directory

[site]
  bucket = "."  # The folder containing your site files
