name = "rashid024.github.io/tools/"
type = "static"

[build]
  command = "echo 'No build command needed'"  # No need for a build step
  directory = "."  # If your static files are in the root

[deploy]
  branch = "main"  # Use your repository's main branch
